.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
https://issues.folio.org/browse/UIOR-1080
While it's helpful for reviewers to help identify …
=> UIOR-1080 Configure GitHub Actions CI pipeline

package.json, src/settings/ConsortiumSettings/ConsortiumSettings.js
https://issues.folio.org/browse/UICONSET-4
While it's helpful for reviewers to help identify …
=> UICONSET-4 Update permissions to manage consortium members

src/settings/Membership/Membership.test.js, src/settings/Membership/validate.test.js
Increase module test coverage at least to 80%
While it's helpful for reviewers to help …
=> Increase module unit test coverage

src/ConsortiumContext.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.test.js, src/eventHandler.js, src/handlers/handleChangeAffilication.js, src/handlers/handleLogin.js, src/handlers/index.js, src/hooks/useCurrentConsortium/useCurrentConsortium.test.js, src/hooks/useUserAffiliations/useUserAffiliations.js, src/hooks/useUserAffiliations/useUserAffiliations.test.js, src/services/consortiaService.js, src/services/index.js, src/utils/checkConsortiumAffiliations.js
=> UICONSET-18 'Switch active affiliation' profile dropdown action

package.json
=> UICONSET-18 act as handler

src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliationModal.js, src/hooks/useUserAffiliations/useUserAffiliations.js, src/hooks/useUserAffiliations/useUserAffiliations.test.js, src/services/consortiaService.js, src/services/consortiaService.test.js
=> UICONSET-18 change endpoints for switch affilication

CHANGELOG.md, package.json, src/Root.js, src/Root.test.js, src/constants.js, src/index.js, src/routes/ConsortiumManager.js, src/routes/ConsortiumManager.test.js, src/routes/index.js, src/settings/ConsortiumSettings/ConsortiumSettings.js, translations/ui-consortia-settings/en.json
https://issues.folio.org/browse/UICONSET-7
https://issues.folio.org/browse/UICONSET-8
- add `app` value into `actAs` property (`package.json::stripes.actAs`);
- introduce consortium manager permissions for "view", "create/edit/delete" and "share";
- update module display name;
- add unit tests.
<details open><summary>Preview</summary>
<p>
</p>
</details>  …
=> UICONSET-7 UICONSET-8 Create "Consortium manager" interface

CHANGELOG.md, package.json, src/constants.js, src/contexts/ConsortiumManagerContext.js, src/hooks/index.js, src/hooks/useTenantKy/index.js, src/hooks/useTenantKy/useTenantKy.js, src/hooks/useTenantKy/useTenantKy.test.js, src/routes/ConsortiumManager/ConsortiumManager.js, src/routes/ConsortiumManager/ConsortiumManager.test.js, src/routes/ConsortiumManager/settings/data-import/DataImportLogs/DataImportLogs.css, src/routes/ConsortiumManager/settings/data-import/DataImportLogs/DataImportLogs.js, src/routes/ConsortiumManager/settings/data-import/DataImportLogs/DataImportLogs.test.js, src/routes/ConsortiumManager/settings/data-import/DataImportLogs/index.js, src/routes/ConsortiumManager/settings/data-import/DataImportSettings.js, src/routes/ConsortiumManager/settings/data-import/constants.js, src/routes/ConsortiumManager/settings/data-import/hooks/index.js, src/routes/ConsortiumManager/settings/data-import/hooks/useDataImportLogs/index.js, src/routes/ConsortiumManager/settings/data-import/hooks/useDataImportLogs/useDataImportLogs.js, src/routes/ConsortiumManager/settings/data-import/hooks/useDataImportLogs/useDataImportLogs.test.js, src/routes/ConsortiumManager/settings/data-import/utils.js, test/jest/fixtures/index.js, test/jest/fixtures/jobExecutions.js, test/jest/helpers/ConsortiumManagerContextProviderMock.js, test/jest/helpers/index.js, translations/ui-consortia-settings/en.json
https://issues.folio.org/browse/UICONSET-123
Make it able to review the status of all import jobs that have run for members.
- use common utils from `@folio/stripes-data-transfer-components`;
- display members' selection and data import logs list in the consortium manager;
- apply pagination and sorting;
- handle errors on data loading;
- write unit tests; …
=> UICONSET-123 View list of import jobs

src/routes/ConsortiumManager/constants.js
=> UICONSET-123 Use `index.js` files as a dynamic import path

src/routes/ConsortiumManager/settings/data-import/hooks/useDataImportLogs/useDataImportLogs.js, src/routes/ConsortiumManager/settings/data-import/hooks/useDataImportLogs/useDataImportLogs.test.js
https://issues.folio.org/browse/UICONSET-123
Get data import logs with the same job statuses as in `ui-data-import` all logs view.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UICONSET-123 Consistent query for data import logs

package.json, src/constants.js, src/hooks/index.js, src/hooks/useTenantPermissions/index.js, src/hooks/useTenantPermissions/useTenantPermissions.js, src/hooks/useTenantPermissions/useTenantPermissions.test.js, src/routes/ConsortiumManager/ConsortiumManager.test.js, src/routes/ConsortiumManager/hooks/index.js, src/routes/ConsortiumManager/hooks/useMemberSelection/index.js, src/routes/ConsortiumManager/hooks/useMemberSelection/useMemberSelection.js, src/routes/ConsortiumManager/hooks/useMemberSelection/useMemberSelection.test.js, src/routes/ConsortiumManager/settings/data-export/DataExportLogs/DataExportLogs.js, src/routes/ConsortiumManager/settings/data-import/DataImportLogs/DataImportLogs.js, src/routes/ConsortiumManager/settings/users/UsersSettings.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSets.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSets.test.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSetsActionsMenu/PermissionSetsActionsMenu.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSetsActionsMenu/index.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/index.js, src/routes/ConsortiumManager/settings/users/general/index.js, test/jest/helpers/buildStripesObject.js, test/jest/helpers/index.js, translations/ui-consortia-settings/en.json
https://issues.folio.org/browse/UICONSET-58
Allow users to view permissions sets for all member libraries they are affiliated with.
---
Requires:
- https://github.com/folio-org/stripes-smart-components/pull/1365
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UICONSET-58 View list of permission sets

src/routes/ConsortiumManager/settings/users/general/PermissionSets/ConsortiumPermissionsSetForm/ConsortiumPermissionsSetForm.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSets.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/constants.js
[UICONSET-59](https://issues.folio.org/browse/UICONSET-59) - Consortia manager - Save/edit permissions set and assign users
- add CRUD component
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UICONSET-59 - fix redirection issue

src/routes/ConsortiumManager/settings/users/general/PermissionSets/ConsortiumPermissionsSetForm/ConsortiumPermissionsSetForm.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/ConsortiumPermissionsSetForm/ConsortiumPermissionsSetForm.test.js, src/temp/PermissionSetForm.js, src/temp/PermissionSetForm.test.js, src/temp/README.md
[UICONSET-59](https://issues.folio.org/browse/UICONSET-59) - Add missing tenantId for permissions modal based on [the comment](https://issues.folio.org/browse/UICONSET-59?focusedCommentId=176328&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-176328)
Ideally all of the PRs involved in breaking changes would be merged in the …
=> UICONSET-59: add tenantId for permissions modal

src/hooks/useTenantPermissions/useTenantPermissions.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSetsCompare/PermissionSetsCompareItem.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/hooks/usePermissionSet.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/hooks/usePermissionSet.test.js
[UICONSET-59](https://issues.folio.org/browse/UICONSET-59)
- rewrite the `usePermissionSet` hook due to conflict with `namespace` for generating `queryKey`
- <video src="https://github.com/folio-org/ui-consortia-settings/assets/116072773/230d6ad1-4f71-466f-8032-ee4e6529eeb5" controles />
Ideally all of the PRs involved in breaking changes would be merged …
=> UICONSET-59: fix caching issue

src/contexts/ConsortiumManagerContext.js
https://issues.folio.org/browse/UICONSET-111
Cloning huge objects blocks the main thread, which affects the user experience.
Use mutation for `.reduce()` accumulator value.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UICONSET-111 Fix performance issue

src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.test.js
Decrease time of affiliation switch
should be merged together with https://github.com/folio-org/stripes-core/pull/1335
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> UICONSET-18 switch affiliations perf

package.json
https://issues.folio.org/browse/UICONSET-112
Deleting shared records requires special permission.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> UICONSET-112 Add missed permission to delete shared record

src/contexts/ConsortiumManagerContext.js
https://issues.folio.org/browse/UICONSET-111
The consortium manager is gonna check the granular permissions of a user, so we need to expand them.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UICONSET-111 Use expanded current user permissions in the consortium manager context

package.json, src/Root.test.js, src/components/ConsortiaControlledVocabulary/ConsortiaControlledVocabulary.js, src/components/ConsortiaEditableList/ConsortiaEditableList.js, src/components/ConsortiaEditableList/index.js, src/components/ConsortiumManagerHeader/ConsortiumManagerHeader.js, src/contexts/ConsortiumManagerContext.js, src/hooks/index.js, src/hooks/useEventEmitter/useEventEmitter.js, src/hooks/useMembersSelection/index.js, src/hooks/useMembersSelection/useMembersSelection.js, src/hooks/useMembersSelection/useMembersSelection.test.js
=> UICONSET-113 fix issues with rerendering

CHANGELOG.md, src/routes/ConsortiumManager/settings/data-export/utils.js, src/routes/ConsortiumManager/settings/data-export/utils.test.js
[UICONSET-142](https://issues.folio.org/browse/UICONSET-142)
While it's helpful for …
=> UICONSET-142: Consortia-settings: format numbers in "Exported" and "Failed" columns

CHANGELOG.md, src/settings/Membership/constants.js, src/settings/Membership/validate.js, src/settings/Membership/validate.test.js, translations/ui-consortia-settings/en.json
https://issues.folio.org/browse/UICONSET-144
Set minimal (2) and maximal (5) length for the `code` field.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> UICONSET-144 Update characters limits of consortia member code

CHANGELOG.md, src/temp/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js
=> UICONSET-148 Manage permissions sets through Consortium Manager fails due to different Okapi token

src/routes/ConsortiumManager/settings/users/general/PermissionSets/hooks/usePermissionSet.test.js
Refs https://issues.folio.org/browse/UICONSET-59
CI pipeline start to fail because of a failing test - https://github.com/folio-org/ui-consortia-settings/actions/runs/6783111972/job/18437448474?pr=90
Use the proper approach to test react hooks.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> Fix test case for `usePermissionSet` hook

CHANGELOG.md, package.json
https://issues.folio.org/browse/UICONSET-149
While it's helpful for reviewers to help …
=> Update the changelog to reflect the v1.0.1 release

CHANGELOG.md, src/components/FindConsortiumMember/FindConsortiumMemberModal/FindConsortiumMemberModal.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSetsEdit/PermissionSetsEdit.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/hooks/usePermissionSet.js, translations/ui-consortia-settings/en.json
https://issues.folio.org/browse/UICONSET-150
While it's helpful for reviewers to help …
=> UICONSET-150 Permissions are not rendered in edit permission set form

CHANGELOG.md
https://issues.folio.org/browse/UICONSET-153
While it's helpful for reviewers to help …
=> Update the changelog to reflect the v1.0.2 release

CHANGELOG.md, src/constants.js
=> UICONSET-157 stripes.route is incorrectly imported from package.json

CHANGELOG.md, src/routes/ConsortiumManager/settings/data-export/utils.js
After refactoring of mod-data-export module, some schemas changes on BE requires addition changes on FE side for sorting.
=> UICONSET-158 UI adjustments for reworked Data Export in Consortia module

src/routes/ConsortiumManager/settings/data-export/utils.js, src/routes/ConsortiumManager/settings/data-export/utils.test.js
=> UICONSET-158 fix failed data-export column after BE refactoring

package.json
Update `stripes-acq-components` version in `package.json` to `~5.1.0`
=> Bump up `stripes-acq-components` version to `~5.1.0`

CHANGELOG.md, package.json, src/settings/CentralOrdering/CentralOrdering.js, src/settings/CentralOrdering/CentralOrdering.test.js, src/settings/CentralOrdering/CentralOrderingForm.js, src/settings/CentralOrdering/index.js, src/settings/ConsortiumSettings/ConsortiumSettings.js, src/settings/Membership/Membership.js, translations/ui-consortia-settings/en.json
https://folio-org.atlassian.net/browse/UICONSET-152
Some consortia - but not all - want all member tenants to have full visibility and access to all locations at all tenants for various workflow purposes. This needs to be configurable system-wide.
https://github.com/folio-org/ui-consortia-settings/assets/88109087/a33de112-0b11-4d70-b137-8e38b306a594 …
=> UICONSET-152 *BREAKING* Implement settings for central ordering across consortium

src/settings/CentralOrdering/CentralOrderingForm.js
https://folio-org.atlassian.net/browse/UICONSET-152
Changelog updated in #113 
https://github.com/folio-org/ui-consortia-settings/assets/88109087/8f4e12b9-d098-4fe1-a36d-dbe850d22532
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UICONSET-152 Disable checkbox for the user without edit perm

CHANGELOG.md, src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.test.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliationModal.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/ConsortiumPermissionsSetForm/ConsortiumPermissionsSetForm.test.js, src/temp/PermissionSetForm.js, src/temp/PermissionSetForm.test.js, src/temp/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js, src/temp/PermissionsAccordion/components/PermissionsModal/PermissionsModal.test.js, translations/ui-consortia-settings/en.json
https://folio-org.atlassian.net/browse/UICONSET-163
Here we updated the translation keys.
=> UICONSET-163: Use Save & close button label stripes-component translation key - all UI modules

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UICONSET-180
Create a hidden (`visible: false`) auxiliary permission set that includes permissions for executing a publications request and use it in the network ordering permission set.
https://github.com/folio-org/ui-consortia-settings/assets/88109087/f6ba8cad-ee20-4398-9d0f-2b31f422f8fa
Ideally all of the PRs …
=> UICONSET-180 Update network ordering permission set to include publications permissions

src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSetsCompare/PermissionSetsCompareItem.test.js
=> UICONSET-159 fix tests

translations/ui-consortia-settings/en.json
add missing translation message id
While it's helpful for reviewers to help identify …
=> add missing translation message id

CHANGELOG.md, src/constants.js, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesSettings.js, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesSettings.test.js, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.js, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.test.js
[UICONSET-162](https://folio-org.atlassian.net/browse/UICONSET-162): Save, edit Authorization policies for consortium.
There is related PR - https://github.com/folio-org/stripes-authorization-components/pull/29
https://github.com/user-attachments/assets/63097035-0a37-473b-8424-614e242411fc
Ideally all of the PRs involved in breaking changes would be merged …
=> UICONSET-162: Save, edit Authorization policies for consortium

src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.js, src/routes/ConsortiumManager/settings/authorization-roles/AuthorizationRolesViewPage.js, src/routes/ConsortiumManager/settings/authorization-roles/utils.js
[UICONSET-159](https://folio-org.atlassian.net/browse/UICONSET-159): fix updated date and updatedBy fields for the roles list
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> UICONSET-159: fix updated date and updatedBy fields for the roles list

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, src/routes/ConsortiumManager/ConsortiumManager.js
=> UICONSET-168 Split consortium manager's navigation links into sections

src/components/FindConsortiumMember/FindConsortiumMember.test.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliation.test.js, src/components/SwitchActiveAffiliation/SwitchActiveAffiliationModal.test.js, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.test.js, src/routes/ConsortiumManager/settings/authorization-roles/Capabilities/CapabilitiesCompareItem/CapabilitiesCompareItem.test.js, src/routes/ConsortiumManager/settings/authorization-roles/UsersCapabilities/UsersCapabilitiesCompareItems/UsersCapabilitiesCompareItems.test.js, src/routes/ConsortiumManager/settings/data-export/utils.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSets.test.js, src/routes/ConsortiumManager/settings/users/general/PermissionSets/PermissionSetsCompare/PermissionSetsCompareItem.test.js, src/settings/CentralOrdering/CentralOrdering.test.js, src/temp/AffiliationSelection/AffiliationSelection.test.js, src/temp/PermissionsAccordion/PermissionsAccordion.test.js
=> UICONSET-189 The cursor does not change to pointer on data-export links

CHANGELOG.md, package.json, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.js, src/routes/ConsortiumManager/settings/authorization-roles/AuthorizationRolesViewPage.js
https://folio-org.atlassian.net/browse/UICONSET-173
https://folio-org.atlassian.net/browse/UICONSET-177
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> UICONSET-173 UICONSET-177 Share authorization Roles and Policies for consortium

CHANGELOG.md, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.js, src/routes/ConsortiumManager/settings/authorization-roles/AuthorizationRolesViewPage.js
https://folio-org.atlassian.net/browse/UICONSET-190
https://github.com/user-attachments/assets/ccb068e6-facc-493d-b34a-c345876e7748
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
=> UICONSET-190 Update the filtering so it works the same for both authorization roles and policies

src/routes/ConsortiumManager/settings/authorization-roles/UsersCapabilities/UsersCapabilitiesCompareItems/UsersCapabilitiesCompareItems.js
https://folio-org.atlassian.net/browse/UICONSET-167
Here we fixed label for accordion in `compare users`
=> UICONSET-167: Compare User capabilities in full screen view

CHANGELOG.md, src/routes/ConsortiumManager/settings/inventory/instances-holdings-items/StatisticalCodes/FieldStatisticalCodeType.js, src/routes/ConsortiumManager/settings/inventory/instances-holdings-items/StatisticalCodes/utils.js, src/routes/ConsortiumManager/settings/inventory/instances-holdings-items/StatisticalCodes/utils.test.js
[UICONSET-200](https://folio-org.atlassian.net/browse/UICONSET-200): ECS - display shared statistical code types on edit mode for member tenants
https://github.com/user-attachments/assets/d1fca27a-11a0-461b-927e-63797e4ebc50
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UICONSET-200: ECS - display shared statistical code types on edit mode for member tenants

CHANGELOG.md, src/routes/ConsortiumManager/settings/authorization-policies/AuthorizationPoliciesView.js
=> UICONSET-208 Restore error handling for policies loading

CHANGELOG.md, src/temp/AssignedUsers/AssignUsers.js, src/temp/AssignedUsers/AssignUsers.test.js, translations/ui-consortia-settings/en.json
[UICONSET-205:](https://folio-org.atlassian.net/browse/UICONSET-205) ECS- Add Tenant identifier to title of Select user modal
https://github.com/user-attachments/assets/d52dfa69-7999-4d81-9bc8-de560ad452ba
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UICONSET-205: ECS- Add Tenant identifier to title of Select user modal

src/constants.js, src/contexts/ConsortiumManagerContext.js, src/hooks/useCurrentUserTenantsPermissions/useCurrentUserTenantsPermissions.js, src/hooks/useCurrentUserTenantsPermissions/useCurrentUserTenantsPermissions.test.js
…
Refs [EUREKA-546](https://folio-org.atlassian.net/browse/EUREKA-546).
While it's helpful …
=> EUREKA-546: use users-keycloak self endpoint in useCurrentUserTenantsPermissions.js if users-keycloak interface is present

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UICONSET-220
=> UICONSET-220 Migrate react-intl and stripes dependencies

CHANGELOG.md, package.json
=> release v3.0.1

CHANGELOG.md, src/routes/ConsortiumManager/settings/authorization-roles/AuthorizationRolesViewPage.js
https://folio-org.atlassian.net/browse/UICONSET-228
Add new `hideUserLink` prop that will display users in assigned users list as a text if enabled
`hideUserLink = true`
`hideUserLink = false`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UICONSET-228 Add newly added 'hideUserLink' to hide user links

CHANGELOG.md, src/components/ConsortiaControlledVocabulary/ConsortiaControlledVocabulary.js, src/components/ConsortiaControlledVocabulary/renderLastUpdated.js, src/components/ConsortiaEditableList/ConsortiaEditableList.js, src/hooks/consortiumManager/useSettings.js, src/hooks/consortiumManager/useSettings.test.js, src/hooks/useCurrentConsortium/useCurrentConsortium.js, src/hooks/useUserAffiliations/useUserAffiliations.js, src/hooks/useUserAffiliations/useUserAffiliations.test.js, src/hooks/useUsers/useUsers.js, src/services/consortiaService.js, src/temp/hooks/useConsortiumPermissions/useConsortiumPermissions.js, src/utils/hydrateSharedRecords.js, test/jest/fixtures/publishCoordinator.js
https://folio-org.atlassian.net/browse/UICONSET-231
After integrating Keycloak, system users now have different IDs in each tenant, whereas previously a user’s ID was consistent across all tenants. In the consortium manager, shared records across tenants are merged into a single record. However, due to the new user ID variability, merging records can result in an unpredictable user ID being assigned to the resulting shared record. This change aims to ensure that, when merging shared records, the metadata (specifically the user ID) from the central tenant is always used, providing consistency and reliability when loading user data.
The merging logic was updated so that, for shared records originating from multiple tenants, the metadata from the central tenant—especially the user ID—is …
=> UICONSET-231 Use metadata from the central tenant for shared records
